name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Caches Node.js dependencies for faster builds
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Set up Node.js (specify your required version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Set up Java if needed (specify your required version/distribution)
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install dependencies and run tests (customize for your project)
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      # Build step (customize for your project)
      - name: Build project
        run: npm run build

      # Upload build artifacts
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./build

  # Optionally, manage stale issues and PRs
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v9
        with:
          stale-issue-message: "This issue has been automatically marked as stale due to inactivity. If this is still relevant, please comment or remove the stale label."
          stale-pr-message: "This pull request has been automatically marked as stale due to inactivity."
          close-issue-message: "Closing this issue due to prolonged inactivity."
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          exempt-issue-labels: "pinned,security"
          exempt-pr-labels: "work-in-progress"
